dist: trusty
sudo: false
cache: pip
language: python
python:
    - "2.7"
# command to install dependencies
install:
    - pip install -r requirements.txt
# command to run tests
script:
  - nosetests
  - flake8 tokenizer.py
